# Generated by Django 4.2.7 on 2023-11-17 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todorepeatapp', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='2001-10-12'),
            preserve_default=False,
        ),
    ]
